### PR TITLE
Cla 2392 update jobs index view

### PR DESCRIPTION
**Pull request by jtwhittington**

### CODE REVIEW

**Comment by jtwhittington** [comment]
screen shot 2016-01-21 at 3 17 45 pm

**Comment by jtwhittington** [comment]
Larger View
screen shot 2016-01-21 at 3 17 25 pm

**Comment by jtwhittington** [comment]
Smaller View with sidebar popped out:
screen shot 2016-01-21 at 3 20 37 pm

**Comment by jimjames99** [comment]
Woah!!!!   Nice looking layout!

**Comment by jtwhittington** [comment]
Still working on how to best handle the table at smaller sizes - anyone who actually uses rjmc feel free to comment on improvements

**Pull request merged**
